<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJcC2IfZ\GanianesCorp_Apps_Web_Backend_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJcC2IfZ/GanianesCorp_Apps_Web_Backend_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJcC2IfZ.legacy');

    return;
}

if (!\class_exists(GanianesCorp_Apps_Web_Backend_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJcC2IfZ\GanianesCorp_Apps_Web_Backend_KernelTestDebugContainer::class, GanianesCorp_Apps_Web_Backend_KernelTestDebugContainer::class, false);
}

return new \ContainerJcC2IfZ\GanianesCorp_Apps_Web_Backend_KernelTestDebugContainer([
    'container.build_hash' => 'JcC2IfZ',
    'container.build_id' => '4cc7a15a',
    'container.build_time' => 1594981672,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJcC2IfZ');
